# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8063f565cbf442116c2910f897f9339bc235946f0081d96b46ac047838d618795e0759d07e9ee560205311772bcbe1b44609156ac56d4f7dd3966455f9c7f54f

test:
  secret_key_base: 204c7aaae943fa1b59be7eb331a84e725e787043a12e6cb17cff0fb25c28d9e4700f107d7509b24116d3469e6b472e9c110440cf2bb6753ccdf07fff35d7c537

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
